version: '3'

services:
  noip:
    container_name: noip-store
    image: coppit/no-ip
    restart: always
    volumes:
      - '/etc/localtime:/etc/localtime'
      - './conf/noip.conf:/config/noip.conf'
  
  nginx:
    container_name: nginx-store
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - './conf/nginx_init.conf:/etc/nginx/nginx.conf:ro'
      - './conf/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './conf/letsencrypt/:/etc/letsencrypt'
      - './conf/tmp/letsencrypt-www:/tmp/letsencrypt/'
      - './web/app:/www'
    depends_on:
      - web

  certbot:
    container_name: certbot-store
    restart: always
    build: ./certbot
    image: certbot:store
    volumes:
      - './conf/letsencrypt/:/etc/letsencrypt/'
      - './conf/tmp/letsencrypt-www:/tmp/letsencrypt/'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      LE_RENEW_ID: nginx-store  # nginx's container name
      # DOMAINS: example.com
      # EMAIL: webmaster@example.com
      WEBROOT_PATH: /tmp/letsencrypt
      EXP_LIMIT: 30
      CHECK_FREQ: 15
    depends_on:
      - noip
      - nginx

  web:
    container_name: web-store
    build: ./web
    image: web:store
    restart: always
    command: sh /run.sh
    volumes:
      - './web/app:/www'
      - './web/run.sh:/run.sh'
      - './web/crontab:/crontab'