version: '3'

services:
  noip:
    container_name: noip-store
    image: coppit/no-ip
    restart: always
    volumes:
      - '/etc/localtime:/etc/localtime'
      - './conf/noip.conf:/config/noip.conf'
  
  letsencrypt:
    container_name: letsencrypt-store
    restart: always
    build: ./letsencrypt
    image: letsencrypt:itlabstore
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt:/etc/letsencrypt
      - ./conf/data/letsencrypt-www:/tmp/letsencrypt
    environment:
      LE_RENEW_ID: nginx-store  # nginx's container name
      # DOMAINS: example.com
      # EMAIL: webmaster@example.com
      WEBROOT_PATH: /tmp/letsencrypt
      EXP_LIMIT: 30
      CHECK_FREQ: 30
    depends_on:
      - noip
      - nginx

  web:
    container_name: itlabstore-store
    build: ./web
    image: itlabstore
    restart: always
    command: sh -c "/run.sh"
    volumes:
      - './web/django:/www'
      - './web/run.sh:/run.sh'
  
  nginx:
    container_name: nginx-store
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "17106:17106"
    volumes:
      # - ./conf/nginx_init.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - ./conf/data/letsencrypt-www:/tmp/letsencrypt
      - './web/django:/www'
    depends_on:
      - web